### ISSUE TITLE
Pokemon-Proto

### ISSUE THREAD

**Issue by laterbreh** [Armax/Pokemon-GO-node-api#1]
Hi, 

Where did you source this protofile? Is this what is needed to decode the player profiles etc? I see proto's here: https://www.reddit.com/r/pokemongodev/comments/4svl1o/guide_to_pokemon_go_server_responses/

Just curious what this one is. 

Just trying to get some more clarity. 

Great work on your project!

**Comment by Armax** [comment]
Hi :) atm I'm using the one from https://github.com/tejado/pokemongo-api-demo but I'm updating some fields in my own version
