### ISSUE TITLE
Get Pokemon data

### ISSUE THREAD

**Issue by seangrogg** [Armax/Pokemon-GO-node-api#102]
Would it be possible to extend this to get data revolving around the user's Pokemon/Items? If you can point me in the direction of some resources I wouldn't mind working on a PR for this to get Pokemon roster fetching included - just don't know where to start.

**Comment by jiaming-jx** [comment]
https://github.com/Armax/Pokemon-GO-node-api/pull/92
Use`Pokeio.GetInventory` after this patch.

**Comment by seangrogg** [comment]
Manually applied #92, works properly. Thank you!
