### ISSUE TITLE
How to get pokemon list from inventary?

### ISSUE THREAD

**Issue by arkdelkaos** [Armax/Pokemon-GO-node-api#105]
I'm writing a "cleaner" for my account. I want it to read the pokemon list from the inventory, then calculate the IV's, and everything under 80% perfection will be given to Oak to make sausages :)

...but I cannot read the inventory:

```
a.GetInventory(function(err,inventory) {
      if (err) throw err;

      console.log(inventory);
    });
```

```
Error: Illegal wire type for field Message.Field .ResponseEnvelop.PokemonData.egg_km_walked_target: 1 (0 expected)
```

How can I access the inventory data? :) 👍

**Comment by jiaming-jx** [comment]
https://github.com/Armax/Pokemon-GO-node-api/issues/102
https://github.com/Armax/Pokemon-GO-node-api/pull/92

**Comment by arkdelkaos** [comment]
WoW...I were too fast cloning the project xD
After a git pull, it do works 👍

**Comment by arkdelkaos** [comment]
Ok, now I can get into the data...but I cannot understand the info :( May you bring some light?

When I print `console.log(inventory)`, I have a nested json like this:

```
{ success: true,
  inventory_delta:
   { original_timestamp_ms: null,
     new_timestamp_ms: Long { low: 454556069, high: 342, unsigned: false },
     inventory_items:
      [ [Object],
        [Object],
        [Object],
        (...)
        [Object],
        ... 71 more items ] } }
```

Then, I think I need to get those objets, so I try with

```
for(var item in inventory.inventory_delta.inventory_items){
        console.log(item.pokemon_id);
     }
```

But then I get a beautiful collection of undefineds :)
What I should do to filter objects from pokemons, and then be able to get their info? I think I may have to convert those object somehow, but I have no clue :(
My goal is to end up having a json kind of like this:

```
{
        id = 1;
        pokemon_id = 2;
        cp = 3;
        stamina_max = 5;
        move_1 = 6;
        move_2 = 7;
        individual_attack = 15;
        individual_defense = 12;
        individual_stamina = 15;
        favorite = yes;
},
{
        id = 2;
        pokemon_id = 22;
        cp = 32;
        stamina_max = 52;
        move_1 = 6;
        move_2 = 7;
        individual_attack = 12;
        individual_defense = 12;
        individual_stamina = 12;
        favorite = no;
}
```

I have seek and found this: https://github.com/Armax/Pokemon-GO-node-api/blob/df4dd21e7a86a16aed5ae004d7e05a6cacf2a976/pokemon.proto
...but I don't know how to work with it :( 

Any help will be very apreciated 👍

**Comment by jiaming-jx** [comment]
Check this.
https://github.com/LASkuma/PokemonStatsGo/blob/master/src/server/utils/getPokemonList.js

**Comment by arkdelkaos** [comment]
Awesome :) That's more that I could have ask for!
