### ISSUE TITLE
[Feature Request] Nearby Pokemon Tracking

### ISSUE THREAD

**Issue by WhataShane** [Armax/Pokemon-GO-node-api#11]
As is demonstrated in this fork of the main Python API:
https://github.com/leegao/pokemongo-api-demo/tree/simulation
If this feature is implemented in this API, it should be trivial to add an additional feature allowing users to scan for local Gyms and Pokestops.

**Comment by Armax** [comment]
I'm already working on it :)

**Comment by WhataShane** [comment]
Still a work in progress?  
I'm attempting this myself but have had a hard time understanding what the original Python "heartbeat" code is doing.

**Comment by WhataShane** [comment]
To start, what is pokemon_pb2 and how (assuming it is) is it implemented in this node adaptation?

**Comment by bencevans** [comment]
@WhataShane if you checkout the first line of that file, you'll see `Generated by the protocol buffer compiler.  DO NOT EDIT!`

This file has been automatically generated by protobuf-compiler from the pokemon.proto file to provide a Python api to generate the proto buffers. 

Instead, in this project [protobuf.js](https://github.com/dcodeIO/protobuf.js) is used for working with the Protocol Buffers datatype.

**Comment by WhataShane** [comment]
Thanks, that cleared things up @bencevans. I've been working on recreating raw_heartbeart line by line in Node and have a seemingly simple question, but I can't find the answer anywhere on the internet: what do the periods in the Python variable names mean?  For example, "m.f1 = ''.join(map(encode, walk))".  Do they actually serve a purpose?  I'm leaning towards no, but I'd like to confirm.

**Comment by Bfindlay** [comment]
@WhataShane its referring to the member variable f1 of the m object?
