### ISSUE TITLE
Suggestion: Discord channel to discuss about the API

### ISSUE THREAD

**Issue by klisman** [Armax/Pokemon-GO-node-api#113]
What you guys think about creating a Discord channel to make a community of developers?
I can help in moderation.

**Comment by cikez** [comment]
This is a great idea, if you create it i'll come.. don't know about others

**Comment by klisman** [comment]
I can create a transfer the ownership to Armax.
What you think @Armax ?

**Comment by filharvey** [comment]
great idea or slack

**Comment by cokeeffekt** [comment]
+1 for slack

**Comment by fr0th** [comment]
There basically already is one... Why make another?

**Comment by cokeeffekt** [comment]
@matoak prove it?

**Comment by Armax** [comment]
we have it, come join us :D https://discord.gg/SCjEQrg channel node_dev
