### ISSUE TITLE
Missing at least one required field for Message

### ISSUE THREAD

**Issue by nirajmchauhan** [Armax/Pokemon-GO-node-api#114]
I updated the package and it stopped catching pokemon. So at line 389 https://github.com/Armax/Pokemon-GO-node-api/blob/master/poke.io.js#L389

I am getting this error:

`[Error: Missing at least one required field for Message .RequestEnvelop.EncounterMessage: .RequestEnvelop.EncounterMessage.spawnpoint_id]`

Full error stack:

> { [Error: Missing at least one required field for Message .RequestEnvelop.EncounterMessage: .RequestEnvelop.EncounterMessage.spawnpoint_id]
>   encoded:
>    { buffer: <Buffer 09 7d a3 f1 c3 ff 91 9d 18 19 5f 20 ad d6 2e 01 41 40 21 97 77 30 bd d8 9f 5d c0 01 01 00 00 00>,
>      offset: 27,
>      markedOffset: -1,
>      limit: 16,
>      littleEndian: false,
>      noAssert: false } }

**Comment by goldhand** [comment]
I added a check before trying to catch a pokemon:

``` javascript
if (currentPokemon.hasOwnProperty('EncounterId') && currentPokemon.hasOwnProperty('SpawnPointId')) {

a.CatchPokemon(currentPokemon, 1, 1.950, 1, 1, function(xsuc, xdat) {
....
```

**Comment by filharvey** [comment]
Is this working for you? I'm having the same issue.

`  

```
                            a.EncounterPokemon(mapPokemon, function(err, encounterResponse)
                            {
                                if(err) {
                                    console.log(err);
                                }

                                console.log (encounterResponse);
                                if (encounterResponse.EncounterStatus == 1)
                                {
                                    var wildPokemon = encounterResponse.WildPokemon;
                                    var pokemon = wildPokemon.pokemon;

                                    var pokemonInfo = a.pokemonlist[parseInt(pokemon.PokemonId)-1];
                                    console.log ("seen: " + pokemonInfo.name);

                                    a.CatchPokemon(mapPokemon, 1.0, 1.95, 1.0, 1, function(err, catchResponse)
                                    {
```

`

and the catch returns no data.

**Comment by goldhand** [comment]
@filharvey you can just edit your install until its fixed. You just need a capital `P`. Check my PR #115

**Comment by filharvey** [comment]
Capture is still returning no information.

**Comment by nirajmchauhan** [comment]
Thanks for the fix, I missed the capital `P`
