### ISSUE TITLE
Why do almost everytime pokemon catch returns Catch Flee

### ISSUE THREAD

**Issue by nirajmchauhan** [Armax/Pokemon-GO-node-api#116]
I guess 90% time whenever I encounter any wild pokemon and try to catch it, I get response as Catch Flee. 

`pokeObject.CatchPokemon(currentPokemon, 1, 1.950, 0.850, 1, function(xsuc, xdat) {});`

Is anyone else facing the same issue?

**Comment by filharvey** [comment]
Can't even get Catch to work properly. Are you Encountering the Pokemon first?

**Comment by gallexme** [comment]
same problem probably soft ban

**Comment by filharvey** [comment]
Yep looks like a soft ban, tried another account and worked ok.

**Comment by filharvey** [comment]
I don't think it is a soft ban issue. I was able to get a Pokémon on my device but not via the bot.  Got a data issue :-(

**Comment by d-pollard** [comment]
@filharvey my repo works for catching perfectly fine - I got 4k star dust in an hour

**Comment by filharvey** [comment]
What is your code for encounter and capture. This has worked before but now is just not working.

**Comment by d-pollard** [comment]
Pull my repo and try it. `ExamplePromises.js` is the file you want

**Comment by filharvey** [comment]
Will do thanks

**Comment by Armax** [comment]
If you keep getting "catch flee" try to play with the official client, try to catch 2 pokemons, if both escape after the first poke ball, you are softbanned

**Comment by Exotheus** [comment]
@d-pollard hi sir how can i put your repo into my bot system?
