### ISSUE TITLE
The Pokemon Trainer Club login not work

### ISSUE THREAD

**Issue by Luzifix** [Armax/Pokemon-GO-node-api#118]
Hey,

i try today the PTC login but its not work.

**Comment by d-pollard** [comment]
Did you change the provider to "ptc" ? I just logged into it with my repo

**Comment by Armax** [comment]
PTC login went offline a lot of time, you can check the status of PTC here http://ispokemongodownornot.com/ (also as @d-pollard said, check if you set provider to ptc)

**Comment by Luzifix** [comment]
forget the ptc, thx for your help :+1:
