### ISSUE TITLE
Use AeonLucid/POGOProtos

### ISSUE THREAD

**Issue by MakuraYami** [Armax/Pokemon-GO-node-api#119]
Since there has already been a major community effort to this "cental" protos repo, and it is more useful to update known protos in one place, I think this api should use their repo, they already offer a nodejs module

https://github.com/rastapasta/pokemon-go-protobuf-node

If its missing anything, it's likely better to submit a PR there.

**Comment by ndugger** [comment]
The complete lack of documentation on the node module makes me scratch my head. While I agree that using a central proto repo would be nice, I haven't the slightest clue on how to use it, since the single example is... well, it's bad.

**Comment by MakuraYami** [comment]
Tbh it doesn't look that complicated looking at the example. Give your buffer and which proto you're parsing. But I have yet to use it so I can't say for sure. If I find the time I'll tinker around with it tomorrow, making a full PR for this repo might be a bit too much for me though. I should at least be able to provide better documentation.

**Comment by KK1423** [comment]
The mentioned module is just a wrapper that combines node-protobuf and a pre-compiled POGOProtos.desc, which can be generated using the python script in POGOProtos. Looking through the structure of POGOProtos, the usage of the messages in this repo, and the docs for node-protobuf should be more than enough to integrate this into the api and replace the current protobufjs + pokemon.proto setup with rastapasta's module.

Considering that tejado's original python api, which this api was ported from, has switched over to AeonLucid's protos, this change seems reasonable.

**Comment by bensleveritt** [comment]
I've actually been working on a protobufjs version of this lib myself, and can +1 @ndugger's complaint with [pokemon-go-protobuf-node](https://github.com/rastapasta/pokemon-go-protobuf-node) being a bit cryptic.

I also would prefer to use protobufjs, since you don't need to precompile the .proto files.

**Comment by MakuraYami** [comment]
@bensleveritt I don't really mind how they are implemented, what is most important is that the [POGOProtos](https://github.com/AeonLucid/POGOProtos) repo can be used in its latest state, preferably with an update script for when there are changes. Since you'll want to run a update script anyway to maintain a up to date package, precompiling isn't a problem. I think the [pokemon-go-protobuf-node](https://github.com/rastapasta/pokemon-go-protobuf-node) is decent, it just lacks a bit of clarity/documentation but as @KK1423 pointed out, its easy enough when you look at the [POGOProtos](https://github.com/AeonLucid/POGOProtos) repo.

**Comment by Armax** [comment]
we are thinking on use it, but atm we prefer to work on our protos, we are also working on rework the protocol builder in a cleaner way

**Comment by st0ffern** [comment]
@MakuraYami i use it. here https://github.com/stoffern/pokemongo-api
and throu Poke.Call() you can call all API functions right out of the box.

We also have sub functions for items, pokemons, forts and so on.. 
example:

```
pokemon =>{
  pokemon.encounter()
  pokemon.catch()
}
```
