### ISSUE TITLE
Tips on not getting soft-banned?

### ISSUE THREAD

**Issue by brettstack** [Armax/Pokemon-GO-node-api#127]
I'm currently walking to, scanning, and attempting to catch at every 100m, but this results in me being insta-soft-banned - does anyone have tips on how to reduce the chance of being soft-banned? How slowly should I be performing these actions?

**Comment by cokeeffekt** [comment]
Hopping countries seems to trigger it for me, so avoid that.

**Comment by d-pollard** [comment]
Is the "soft ban" when they are fleeing instantly?

**Comment by cokeeffekt** [comment]
fleeing instantly is typically from multiple logins to the same account.

**Comment by d-pollard** [comment]
I think we should make some standards to kind of "detect" why things are happening

**Comment by cokeeffekt** [comment]
there is no event for why, we can guess, most of peoples problems stem from, multiple logins, hopping large distances too quickly, or not understanding async and triggering multiple events at once. Don't do these things and there shouldn't be an issue. Another thing to mention is the examples.js doesn't take async into account.

**Comment by d-pollard** [comment]
@cokeeffekt I don't even use this library any more. I forked it and made it way better lol.

**Comment by cokeeffekt** [comment]
@d-pollard if its way better why not submit a pull request

**Comment by d-pollard** [comment]
@cokeeffekt  - our repos have deviated significantly. Others usually end up putting my code in here. My repo uses promises and I am moving to ES6, whereas this one wants to stay with ES5 only.

**Comment by cokeeffekt** [comment]
eh, i dunno i looked at your repo doesn't seem to be worth the swap. also most of the cb functions are promisify safe (a few need fixing) seems like time would be better spent working with the core project, rather than forking to start your own party. Esp since my latest pull requests you are falling behind on features. I only have more to come :P

**Comment by d-pollard** [comment]
@cokeeffekt - your features are childsplay whilst I'm busy working on fort take over and eventual - fort "DOP" (denial of play) for rival teams.

**Comment by jaredallard** [comment]
Commenting code wise, I can somewhat agree that the state of this repo is concerning. The amount of technical debt in this lib is insane, the convention is a bit odd, using callback constructors but then using the same instance as opposed to returning a new one.

IMO a fork would be nice of this, but not of the current state. 

Tips soft ban wise -- noticed that keeping requests at a similar pattern of the app works nicely, deviation of reasonable walking time as well, basically think like the app prevents most of it.

**Comment by d-pollard** [comment]
Also, adding in lodash is overhead that this already - large library doesn't need.

**Comment by jimmywarting** [comment]
@d-pollard if you want to work with ES6 and promises - have a look at [pokemongo-api](https://github.com/stoffern/pokemongo-api)

**Comment by brettstack** [comment]
What is fort DOP? I agree with Patrick, it makes more sense to keep it to
one repo. While I prefer ES6 and promises, it's not worth forking the
community over. It's also a little rude to call someone's PRs childs play...

**Comment by Armax** [comment]
we are working on a more realistic walk function

**Comment by d-pollard** [comment]
@breandr ...I literally explained DOP right after I coined the acronym.

**Comment by brettstack** [comment]
And yet you didn't provide sufficient explanation of "Denial of Play". If you're going to try coin new terms, you should probably make it clear what they mean. :)

**Comment by d-pollard** [comment]
@breandr any developer knows what a "Denial of..." means...seems to me like you like to play the role...

**Comment by d-pollard** [comment]
Hell, anyone who knows English could figure out what it means lmfao @breandr
