### ISSUE TITLE
Catch not work, "missing at least one required field for message ..."

### ISSUE THREAD

**Issue by engvie** [Armax/Pokemon-GO-node-api#129]
I get this error when I try example (b.), the problem occures here:
`b.EncounterPokemon(currentPokemon, function(suc, dat) {`

> /Users/USER/Sites/nodePokemon/node_modules/protobufjs/dist/protobuf.js:2661
>                         throw(e);
>                         ^
> 
> Error: Missing at least one required field for Message .RequestEnvelop.EncounterMessage: .RequestEnvelop.EncounterMessage.spawnpoint_id
>     at Error (native)
>     at ProtoBuf.Reflect.MessagePrototype.encode (/Users/USER/Sites/nodePokemon/node_modules/protobufjs/dist/protobuf.js:3118:27)
>     at MessagePrototype.encode (/Users/USER/Sites/nodePokemon/node_modules/protobufjs/dist/protobuf.js:2657:27)
>     at Pokeio.self.EncounterPokemon (/Users/USER/Sites/nodePokemon/poke.io.js:392:65)
>     at /Users/USER/Sites/nodePokemon/run.js:47:27
>     at /Users/USER/Sites/nodePokemon/poke.io.js:277:7
>     at Request._callback (/Users/USER/Sites/nodePokemon/poke.io.js:143:16)
>     at Request.self.callback (/Users/USER/Sites/nodePokemon/node_modules/request/request.js:187:22)
>     at emitTwo (events.js:100:13)
>     at Request.emit (events.js:185:7)

**Comment by Armax** [comment]
we are fixing it just wait the next push
