### ISSUE TITLE
INVALID_REQUEST: Missing the \'address\', \'bounds\', \'components\', \'latlng\' or \'place_id\' parameter

### ISSUE THREAD

**Issue by loretoparisi** [Armax/Pokemon-GO-node-api#13]
Always getting this request error

``` shell
{ error_message: 'Invalid request. Missing the \'address\', \'bounds\', \'components\', \'latlng\' or \'place_id\' parameter.',
  results: [],
  status: 'INVALID_REQUEST' }
```

**Comment by Armax** [comment]
can you please give me your location object?

**Comment by Armax** [comment]
can you please give me your location object?

**Comment by loretoparisi** [comment]
I used the example one:

``` javascript
//Set environment variables or replace placeholder text
var location = process.env.PGO_LOCATION || {'type':'name','name':'Times Square'};
```

**Comment by loretoparisi** [comment]
I have also tried like this

``` javascript
var location = process.env.PGO_LOCATION || {'type':'address','name':'New York, Times Square'};
```

**Comment by Armax** [comment]
try with an other location name near you, full address maybe

**Comment by loretoparisi** [comment]
@Armax and what about the `type` value?

**Comment by Armax** [comment]
The type value should be "name" or "coords" we are updating our docs, anyway just tested with the one provided in the example and I didn't get any errors, I will look at it more now

**Comment by loretoparisi** [comment]
@Armax I'm using Google oauth

**Comment by Armax** [comment]
Google oauth is not implemented yet, this is why you get the error, we are doing it right now

**Comment by loretoparisi** [comment]
@Armax ah so 👍  let's wait then :)

**Comment by Armax** [comment]
we now have Google auth, just set 
`var username = process.env.PGO_USERNAME || 'email@gmail.com'; 
var password = process.env.PGO_PASSWORD || 'password';
var provider = process.env.PGO_PROVIDER || 'google';`

**Comment by loretoparisi** [comment]
@Armax Great, just fix the require in the example:

``` javascript
var Pokeio = require('pokemon-go-node-api')
```

**Comment by loretoparisi** [comment]
Woah it worked!

``` shell
[i] Logging with user: xxxxx
[i] Received API Endpoint: xxxxxx
[i] Current location: Times Square
[i] lat/long/alt: : 40.759011 -73.9844722 0
[i] Logged in!
[i] Username: xxxxx
[i] Poke Storage: 250
[i] Item Storage: 350
[i] Pokecoin: 0
[i] Stardust: 100
```

💯

**Comment by Armax** [comment]
The example pick the module from the same directory and the file is called poke.io.js, anyway I will fix it in the next commit :)
