### ISSUE TITLE
Error on Capturing

### ISSUE THREAD

**Issue by filharvey** [Armax/Pokemon-GO-node-api#130]
Before people say it is a soft ban it is not.  Here is my log from 2 runs. I am actually capturing the Pokemon, but I'm getting an error in the response.

`

Debugger listening on port 15454
[34.01325002677071,-118.49324876210429]
[i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/123/rpc
1[i] Current location: 297-303 Colorado Ave, Santa Monica, CA 90401, USA
1[i] lat/long/alt: : 34.01325002677071 -118.49324876210429 10
[i] Logged in!
1[i] Username: pokemonnode
1[i] Poke Storage: 250
1[i] Item Storage: 350
1[i] Pokecoin: 0
1[i] Stardust: 2600
egg: 5km
pokemon: Ekans, seen: 4 - captured: 3
item: 201, count: 10
pokemon: Sandshrew, seen: 1 - captured: 1
pokemon: Nidoran ♀, seen: 1 - captured: 1
pokemon: Nidorina, seen: 1 - captured: 1
pokemon: Zubat, seen: 8 - captured: 4
pokemon: Paras, seen: 1 - captured: 1
pokemon: Venonat, seen: 1 - captured: 1
pokemon: Diglett, seen: 2 - captured: 1
egg: 5km
pokemon: Meowth, seen: 4 - captured: 4
pokemon: Mankey, seen: 1 - captured: 1
pokemon: Growlithe, seen: 3 - captured: 2
pokemon: Machop, seen: 2 - captured: 2
pokemon: Geodude, seen: 4 - captured: 2
egg: 5km
pokemon: Squirtle, candy: 3
egg: 5km
item: 401, count: 2
pokemon: Pidgey, candy: 3
pokemon: Ekans, candy: 9
pokemon: Sandshrew, candy: 3
item: 901, count: 1
pokemon: Nidoran ♀, candy: 6
egg: 5km
item: 101, count: 10
pokemon: Zubat, candy: 12
pokemon: Paras, candy: 3
pokemon: Venonat, candy: 3
13280/15000
pokemon: Diglett, candy: 3
pokemon: Meowth, candy: 12
pokemon: Mankey, candy: 3
pokemon: Growlithe, candy: 6
pokemon: Squirtle, seen: 1 - captured: 1
item: 1, count: 117
pokemon: Machop, candy: 6
pokemon: Pidgey, seen: 1 - captured: 1
egg: 5km
pokemon: Geodude, candy: 6
pokemon: Spearow, seen: 1
1[i] Current location: 297-303 Colorado Ave, Santa Monica, CA 90401, USA
1[i] lat/long/alt: : 34.01325002677071 -118.49324876210429 10
1[+] There is a Sandshrew at 200 meters
1[+] There is a Zubat at 200 meters
1[+] There is a Zubat at 34.01349140328949, -118.49319343093258 - 27.320067790703984
moving to: 34.01349140328949, -118.49319343093258 - dist: 27.320067790703984
1[i] Current location: Santa Monica, CA 90401, USA, dist 22.320067791473498
1[i] Current location: Santa Monica, CA 90401, USA, dist 17.32006779212055
1[i] Current location: Santa Monica, CA 90401, USA, dist 12.320067791985604
1[i] Current location: Santa Monica, CA 90401, USA, dist 7.3200677922371264
1[i] Current location: Santa Monica, CA 90401, USA
1[i] lat/long/alt: : 34.01342672949289 -118.49320825623185 10
1[+] There is a Sandshrew at 200 meters
1[+] There is a Zubat at 200 meters
1[+] There is a Zubat at 34.01391499187082, -118.4924635506569 - 87.5158823949939
moving to: 34.01391499187082, -118.4924635506569 - dist: 87.5158823949939
1[i] Current location: Santa Monica, CA 90401, USA, dist 82.51588239395375
1[i] Current location: Santa Monica, CA 90401, USA, dist 77.51588239308991
1[i] Current location: Santa Monica, CA 90401, USA, dist 72.51588239553286
1[i] Current location: Santa Monica, CA 90401, USA, dist 67.51588239526146
1[i] Current location: Santa Monica, CA 90401, USA, dist 62.51588239545319
1[i] Current location: Santa Monica, CA 90401, USA, dist 57.515882397278
1[i] Current location: Santa Monica, CA 90401, USA, dist 52.51588239578898
1[i] Current location: Santa Monica, CA 90401, USA, dist 47.51588239425767
1[i] Current location: Santa Monica, CA 90401, USA, dist 42.51588239752003
1[i] Current location: Santa Monica, CA 90401, USA, dist 37.51588239925274
1[i] Current location: Santa Monica, CA 90401, USA, dist 32.515882401888014
1[i] Current location: Santa Monica, CA 90401, USA, dist 27.515882398706424
1[i] Current location: Santa Monica, CA 90401, USA, dist 22.515882399660256
1[i] Current location: Santa Monica, CA 90401, USA, dist 17.515882400601672
1[i] Current location: Santa Monica, CA 90401, USA, dist 12.515882401518873
1[i] Current location: Santa Monica, CA 90401, USA, dist 7.515882404065212
1[i] Current location: Santa Monica, CA 90401, USA
1[i] lat/long/alt: : 34.01387305976426 -118.49252750626721 10
1[+] There is a Zubat at 200 meters
1[+] There is a Zubat at 34.01391499187082, -118.4924635506569 - 7.515882404065212
1[+] Encountering Zubat at 34.01391499187082, -118.4924635506569 - 7.515882404065212
moving to: 34.013523, -118.492144 - dist: 52.57953892700899
1[+] capturing Zubat at 34.01391499187082, -118.4924635506569 - 7.515882404065212
[Error: Illegal wire type for field Message.Field .ResponseEnvelop.CaptureAward.ActivityType: 2 (0 expected)]

`

and this is the second run

`

Debugger listening on port 15454
[i] Received Google access token!
[i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/123/rpc
1[i] Current location: 366-392 Colorado Ave, Santa Monica, CA 90401, USA
1[i] lat/long/alt: : 34.01364003959731 -118.49227222203889 10
[i] Logged in!
1[i] Username: pokemonnode
1[i] Poke Storage: 250
1[i] Item Storage: 350
1[i] Pokecoin: 0
1[i] Stardust: 2700
egg: 5km
pokemon: Ekans, seen: 4 - captured: 3
item: 201, count: 10
pokemon: Sandshrew, seen: 1 - captured: 1
pokemon: Nidoran ♀, seen: 1 - captured: 1
pokemon: Nidorina, seen: 1 - captured: 1
pokemon: Zubat, seen: 9 - captured: 5
pokemon: Paras, seen: 1 - captured: 1
pokemon: Venonat, seen: 1 - captured: 1
pokemon: Diglett, seen: 2 - captured: 1
egg: 5km
pokemon: Meowth, seen: 4 - captured: 4
pokemon: Mankey, seen: 1 - captured: 1
pokemon: Growlithe, seen: 3 - captured: 2
pokemon: Machop, seen: 2 - captured: 2
pokemon: Geodude, seen: 4 - captured: 2
egg: 5km
pokemon: Squirtle, candy: 3
egg: 5km
item: 401, count: 2
pokemon: Pidgey, candy: 3
pokemon: Ekans, candy: 9
pokemon: Sandshrew, candy: 3
item: 901, count: 1
pokemon: Nidoran ♀, candy: 6
item: 101, count: 10
pokemon: Zubat, candy: 15
pokemon: Paras, candy: 3
pokemon: Venonat, candy: 3
13490/15000
pokemon: Diglett, candy: 3
pokemon: Meowth, candy: 12
pokemon: Mankey, candy: 3
pokemon: Growlithe, candy: 6
pokemon: Squirtle, seen: 1 - captured: 1
item: 1, count: 116
pokemon: Machop, candy: 6
pokemon: Pidgey, seen: 1 - captured: 1
egg: 5km
pokemon: Geodude, candy: 6
pokemon: Spearow, seen: 1

`

As you can see initially I have seen 8 Zubat and captured 4. the second time I have seen 9 and captured 5.

But I'm sometimes seeing this error

**1[+] capturing Zubat at 34.01391499187082, -118.4924635506569 - 7.515882404065212
[Error: Illegal wire type for field Message.Field .ResponseEnvelop.CaptureAward.ActivityType: 2 (0 expected)]**

on capture.

**Comment by filharvey** [comment]
Changing the proto to this is working

  message CatchPokemonResponse {
      optional CatchStatus Status = 1;
      optional double MissPercent = 2;
        // optional uint64 CapturedPokemonId = 3;
      //optional CaptureAward CaptureAward = 4;

**Comment by Armax** [comment]
gonna fix in the next push :)

**Comment by filharvey** [comment]
You know what the issue is?
