### ISSUE TITLE
WildPokemon either empty or small amount.

### ISSUE THREAD

**Issue by ButchMonkey** [Armax/Pokemon-GO-node-api#133]
The WildPokemon array seems to always either empty or small amount.
`[{"EncounterId":{"low":570066557,"high":1837351680,"unsigned":true},"LastModifiedMs":{"low":580492510,"high":342,"unsigned":false},"Latitude":52.07300839137805,"Longitude":-1.3258175187096903,"SpawnPointId":"487726438ff","pokemon":{"Id":null,"PokemonId":90},"TimeTillHiddenMs":655742}]`

Have checked with mobile app and other location based tools and there should be at least a few more. The NearbyPokemon array doesnt match up either and says there are more.

This is the code I am using - 

```
for (var i = hb.cells.length - 1; i >= 0; i--) {
    if(hb.cells[i].WildPokemon[0]) 
    {
        console.log(JSON.stringify(hb.cells[i].WildPokemon));
     }
```

and for nearby - 

```
for (var i = hb.cells.length - 1; i >= 0; i--) {
    if(hb.cells[i].NearbyPokemon[0]) 
    {
        console.log(JSON.stringify(hb.cells[i].NearbyPokemon));
     }
```

Also, while I'm here-
What are the "high" and "low" attributes of some fields, i.e. EncounterId?

Thanks

**Comment by coolaj86** [comment]
- This library only returns nearby pokemon (10 s2 cells on either side of you). Your client needs to update the location and heartbeat again to scan for pokemon that are farther away
- EncounterId is a 64-bit integer See https://github.com/dcodeIO/long.js/issues/34 for how to convert it back to base64

**Comment by elijthomas** [comment]
How do you 'update the location' setlocation doesn't update the location as it stays the same in the heartbeat

**Comment by reecube** [comment]
Since a few days, I have the same issue. I have a script and didn't change its content, but since a few days the script only shows 0-3 WildPokemon. Before I've had about 20 WildPokemon for the same radius (and yes I did update the location to increase the radius).

And compared with my Pokemon GO App, the WildPokemon-data is not complete.
