### ISSUE TITLE
RequestEnvelop.EncounterMessage is not a constructor

### ISSUE THREAD

**Issue by sebastianwachter** [Armax/Pokemon-GO-node-api#135]
Every time I try to call EncounerPokemon() I am getting the error of the title.
I searched the pokemon.proto file for a message called EncounterMessage and it's actually missing.

**Comment by andreivreja** [comment]
Hey there, I can assure you it's not missing. Maybe you've checked the wrong file.

[master/pokemon.proto](https://github.com/Armax/Pokemon-GO-node-api/blob/master/pokemon.proto) line 65.

**Comment by sebastianwachter** [comment]
I used npm install and checked my local files and there it is missing. In line 65 is nothing and that gets followed by "message Unknown7" in line 66.
<a href="http://hastebin.com/efugoxunob.avrasm">This is my pokemon.proto</a>

**Comment by sebastianwachter** [comment]
Okay I did a update and now it's working. Was a bit strange since I initially created this project yesterday.
Nevertheless thank you.
