### ISSUE TITLE
Difference between ReleasePokemon and TransferPokemon

### ISSUE THREAD

**Issue by dougiefresh49** [Armax/Pokemon-GO-node-api#137]
looking through the code and I'm not too sure what the functional difference is between [ReleasePokemon](https://github.com/Armax/Pokemon-GO-node-api/blob/master/poke.io.js#L494)  and [TransferPokemon](https://github.com/Armax/Pokemon-GO-node-api/blob/master/poke.io.js#L376). Anyone know this?

If there is a difference, where is release used in the actual game? I know transfer is used like so
`Pokebutton --> Pokemon --> select pokemon --> scroll to bottom --> select transfer`

thanks for the help

**Comment by cokeeffekt** [comment]
nothing, there was a dupe function created by myself and someone else a few hours later recreated it unknowingly i assume.

**Comment by dougiefresh49** [comment]
ah ok, thats what I was thinking.

Thanks!
