### ISSUE TITLE
CatchPokemonResponse null values?

### ISSUE THREAD

**Issue by brettstack** [Armax/Pokemon-GO-node-api#138]
I'm getting null values for response to CatchPokemon - any ideas what this means?

`{ Status: null, MissPercent: null, CaptureAward: null }`

**Comment by sameerkanda** [comment]
Soft ban from Pokemon GO: https://www.reddit.com/r/pokemongo/comments/4u0av6/soft_ban_research/

**Comment by zaggaz** [comment]
I'm getting the same, is that a ban on a particular account then?

**Comment by akateiva** [comment]
It will also return null if your pokemon storage is full.
EDIT: Also if you run out of pokeballs.

**Comment by brettstack** [comment]
My experience is that I receive status 3 if I am banned. Thanks for the tip
on poke storage.

**Comment by sameerkanda** [comment]
I take that back, I think null = no pokeballs or storage full or something (not a soft ban). I was getting banned at the same time as my pokeballs ran out, so must have confused the two.
