### ISSUE TITLE
Error: CAS is Unavailable! There was an error trying to complete your request. Please notify your support desk or try again.

### ISSUE THREAD

**Issue by reecube** [Armax/Pokemon-GO-node-api#143]
Since 2 or 3 days, I always get the following error: 

```
CAS is Unavailable! There was an error trying to complete your request. Please notify your support desk or try again.
```

Sometimes I get a successfull response, but this does not happen a lot.
The pgo-app works perfectly fine and services like Pokevision.com are online too, so it can't be the server.

**Comment by reecube** [comment]
Found the actual problem: This error occures when you keep the pokemon library in memory.

**Comment by gallexme** [comment]
sounds like firewall issues 
which means issues in your network
-> not this libs fault?

**Comment by reecube** [comment]
@gallexme I'm not sure about this. If this would really be firewall issues, it would be very weird. Also I've tested it on different servers and clients and I have the same issue everywhere (even different networks/firewalls).

Also I figured out, that the problem occures on the 2nd request after my node started. This is very weird, I use the api with express. After 'node .', the first request is successful and then every other request fails, but when I quit node and restart it, the first request is successful again. For me it looks like some kind of cache or scope that is still alive until i stop node.

**Comment by d-pollard** [comment]
Lol you must be digging into the code without actually looking at it (or understanding it). @reecube I know exactly where this comes from and why, but the real question is - why are you trying to re-invent the wheel?

**Comment by reecube** [comment]
@d-pollard what do you mean with re-invent the wheel?

**Comment by d-pollard** [comment]
@reecube that "error" only occurs for people who don't know how to properly parse the login information. Which leads me to believe you are trying to re-create the login process from this library.

**Comment by reecube** [comment]
@d-pollard well I didn't. I've only run pgoModule.init(...) but maybe the point is, that this doesn't work if you call it twice, even if you call a new module instance. I didn't touch the code of this api at all and I didn't write any code for login-process or similar myself. All these errors are thrown by the api.

**Comment by reecube** [comment]
As mentioned before, if I don't run the init function twice, it works. But this should be fixed in code anyway, because maybe you want to do logins with different accounts without restarting your node application.

**Comment by d-pollard** [comment]
@reecube for the new process, are you calling...
`var Pokeio = require('pokemon-go-node-api').Pokeio`
Then
`var login1 = new Pokeio;`
`var login2 = new Pokio;`
