### ISSUE TITLE
s2geometry-node and node-gyp build error

### ISSUE THREAD

**Issue by arkdelkaos** [Armax/Pokemon-GO-node-api#147]
```
emote: make: Leaving directory `/var/lib/openshift/56a101f97628e1ed0c0000ad/app-root/runtime/repo/node_modules/pokemon-go-node-api/node_modules/s2geometry-node/build'
remote: gyp ERR! build error
remote: gyp ERR! stack Error: `make` failed with exit code: 2
remote: gyp ERR! stack     at ChildProcess.onExit (/opt/rh/nodejs010/root/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
remote: gyp ERR! System Linux 2.6.32-573.12.1.el6.x86_64
remote: gyp ERR! command "node" "/opt/rh/nodejs010/root/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote: gyp ERR! cwd /var/lib/openshift/56a101f97628e1ed0c0000ad/app-root/runtime/repo/node_modules/pokemon-go-node-api/node_modules/s2geometry-node
remote: gyp ERR! node -v v0.10.35
remote: gyp ERR! node-gyp -v v3.2.0
remote: gyp ERR! not ok
remote: npm info s2geometry-node@1.3.1 Failed to exec install script
remote: npm ERR! Linux 2.6.32-573.12.1.el6.x86_64
remote: npm ERR! argv "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"
remote: npm ERR! node v0.10.35
remote: npm ERR! npm  v2.14.13
remote: npm ERR! code ELIFECYCLE
remote:
remote: npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
```

I'm trying to upload my project to openshift, and I keep getting this build error.
I had try everything I could think of, but my options are limited being a free hosting for open source projects.
Everything works great on my side...but I don't know where to attack this problem. 
May you throw some insight on this? :) I'll contact openshift's tech, meanwhile

**Comment by arkdelkaos** [comment]
After much hunting info around...I've come to this:
https://github.com/icflorescu/openshift-cartridge-nodejs/issues/49

It's seems there is no hope :(
Maybe its there some kind of alternative? another lib that doesn't depend on node-gyp?
I didn't expect this...everything works fine, and then founding that all that work means nothing before the mighty-outdated server xD

**Comment by ArthurGerbelot** [comment]
Same problem with MeteorJS 1.3.5 (who run a Node 0.10.46).
But `s2geometry-node` (and so `node-gyp`) use V8 namespace introduced on 0.11

**Comment by necm1** [comment]
same here...

**Comment by klisman** [comment]
I had the same problem before. 
Possible solutions https://github.com/billyriantono/s2geometry-node/issues/12

**Comment by arkdelkaos** [comment]
In the end I'm gonna change to Heroku :) There all goes smooth.
I think that openshift isn't going to do much, knowing that their node base is 0.10, and they just don't care enough to upgrade.

**Comment by necm1** [comment]
@klisman & @arkdelkaos 
https://github.com/billyriantono/s2geometry-node/issues/14#issuecomment-235588095 <- worked for me.

**Comment by coolaj86** [comment]
Fixed in https://github.com/Armax/Pokemon-GO-node-api/pull/165 by using pure JavaScript - no C++ or compiler necessary.

**Comment by beuted** [comment]
Build is going fine on windows 7 but now calling PokeIo.heartbreak gives me:

```
C:\src\dkj\performance-hunting\node_modules\pokemon-go-node-api\poke.io.js:49
  var origin = S2.latLngToQuadkey(lat, lng, level);
                  ^

TypeError: S2.latLngToQuadkey is not a function
    at getNeighbors (C:\src\dkj\performance-hunting\node_modules\pokemon-go-node-api\poke.io.js:49:19)
    at Pokeio.self.Heartbeat (C:\src\dkj\performance-hunting\node_modules\pokemon-go-node-api\poke.io.js:261:16)
    at Timeout.setInterval [as _repeat] (C:\src\dkj\performance-hunting\index.js:59:20)
    at Timeout.wrapper [as _onTimeout] (timers.js:421:11)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by coolaj86** [comment]
I need help fixing https://github.com/coolaj86/s2-geometry-javascript/issues/6 before this can be merged in.

However, you can use my fork in the meantime: https://github.com/Daplie/Pokemon-GO-node-api

You can test that it (usually) works with my Pokémap server: https://github.com/Daplie/node-pokemap

**Comment by jdpnielsen** [comment]
Closing issue for now. Please continue discussion on the pr by @coolaj86.
