### ISSUE TITLE
Abillity to recieve level up rewards

### ISSUE THREAD

**Issue by WesVleuten** [Armax/Pokemon-GO-node-api#155]
As far as I am aware there is no current way to recieve these rewards. This feature would be great for automation

**Comment by antonrez89** [comment]
Does anybody know how to get the current user level?

**Comment by rraziel** [comment]
It's message 128: LEVEL_UP_REWARDS.
In the message you specify your level, in the response you get a list of items (awarded and unlocked)
It'd probably be easier if this project used the POGOProtos files

**Comment by cokeeffekt** [comment]
i added a pull request for this.
https://github.com/Armax/Pokemon-GO-node-api/pull/154
