### ISSUE TITLE
Every pokemon flees

### ISSUE THREAD

**Issue by bartjakobs** [Armax/Pokemon-GO-node-api#156]
Using the example.js (second example in the file), Pokémon can be encountered and tried to catch. It seems that every time the program finds a Pokémon, the Pokémon flees. Are the arguments for Pokeio.CatchPokemon documented and has anyone found an ideal configuration / algorithm or do the Pokémon Go servers recognize this api client and try to prevent cheating?

**Comment by gallexme** [comment]
u are softbanned
probably teleported to far without waiting a reasonable time

**Comment by bartjakobs** [comment]
@gallexme thanks
