### ISSUE TITLE
How can i close the connection or stop the scan in javascript?

### ISSUE THREAD

**Issue by psyzz** [Armax/Pokemon-GO-node-api#168]
Hi, thanks for your job,

i'm looking to stop the Heartbeat but it seems to never stop ?

How can i close the connection ? Like 

```

var a = new PokemonGO.Pokeio();

a.Disconnect():

```

Thanks!

**Comment by jiaming-jx** [comment]
If you are using the provided example, you can see [this line](https://github.com/Armax/Pokemon-GO-node-api/blob/master/example.js#L49) called `setInterval(function, 5000)` which means the heartbeat function would be called every 5 seconds. 

Here are two ways to 'stop' it.
1. Drop the `setInterval` call, simply call the heartbeat function whenever you want
2. Save the return value of `setInterval` into a variable and call `clearInterval` later, e.g., `var a = setInterval(somefunction, 5000); clearInterval(a);`
