### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by BlackRosie** [Armax/Pokemon-GO-node-api#174]
check out: https://github.com/BlackRosie/PokemonGoNodeDashboard

You can login, start the auto farmer, and walk around on a map using the arrow keys.

**Comment by natedoesweb** [comment]
I debated doing something like this, but don't want to take away the aspect that makes this game fun. However, if anyway wants to work on a text adventure styled implementation and make it open source I'd be down to contribute.

**Comment by cokeeffekt** [comment]
@BlackRosie i think we are working on very similar projects, https://github.com/cokeeffekt/pokebot-ui

**Comment by BlackRosie** [comment]
@cokeeffekt well look at that ^_^ great minds like to have fun do they not.

**Comment by cokeeffekt** [comment]
I was just looking through your project, we really have been in parallel here. 👍 on the project looks good.

**Comment by kurotsukikaitou** [comment]
Another parallel work :3
https://github.com/kurotsukikaitou/PokeGo-Slave
