### ISSUE TITLE
DecimatedSpawnPoint no longer provided in cells

### ISSUE THREAD

**Issue by natedoesweb** [Armax/Pokemon-GO-node-api#175]
I've been using the DecimatedSpawnPoint array to triangulate an approx location for nearby pokemon so I don't have to move my player to scan for wild pokemon. It doesn't appear to get passed anymore, and I'm also not receiving all the nearby pokemon in the array.

Is this a change on Niantic's end that's preventing this data from coming through?

**Comment by BlackRosie** [comment]
This appears to happen to me when the servers are under heavy loads

**Comment by natedoesweb** [comment]
I hope that's all it is. I have a slack bot scanning Pokemon around my office and I've finally got it running solid and then this happens, haha.

**Comment by BlackRosie** [comment]
hahah the feels
