### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by brettstack** [Armax/Pokemon-GO-node-api#178]
Is it just me or are there a lot of "No result" errors being returned?

```
} else if (!f_ret || !f_ret.payload || !f_ret.payload[0]) {
    return callback('No result');
}
```

**Comment by natedoesweb** [comment]
Not just you. I provided my work around here: #148 
I'm not sure what the source of this problem is, but it seems the the session times out.

**Comment by brettstack** [comment]
Thanks for your response. This is sometimes happening to me immediately after I log in though... And other times just randomly from heartbeat. Are you seeing same behaviour? Maybe the servers are being flakey, or maybe they changed something on the servers... Or maybe I just pulled in something here that's causing it.

**Comment by WiS3** [comment]
It happens rarely to me also.. sometimes just after login, and sometimes from heartbeat

**Comment by natedoesweb** [comment]
I've never seen it happen after login, but maybe it started happening after i implemented my work around

**Comment by predator747** [comment]
Same here! I often getting No result

**Comment by predator747** [comment]
I heard something that Niantic limited the requests per seconds to 3...
so your timeout should be about that before starting a new mapscan

**Comment by AlexZaccaria** [comment]
Ok, i can confirm this @predator747 
ReScans gets No Result within 500ms

```
if(err)
{
    console.log(err + "["+Pokeio.playerInfo.latitude+", "+Pokeio.playerInfo.longitude+"]");
    setTimeout(function() { Pokeio.Heartbeat(MyHeartbeat); }, 100);
    return;
}
```

No result[45.44242190000001, 9.161924299999988]
No result[45.44242190000001, 9.161924299999988]
No result[45.44242190000001, 9.162924299999988]
No result[45.44242190000001, 9.162924299999988]
No result[45.44242190000001, 9.163924299999987]
No result[45.44242190000001, 9.163924299999987]
No result[45.44242190000001, 9.164924299999987]
No result[45.44242190000001, 9.164924299999987]
No result[45.44242190000001, 9.165924299999986]
No result[45.44242190000001, 9.165924299999986]
No result[45.44242190000001, 9.166924299999986]
No result[45.44242190000001, 9.166924299999986]
No result[45.44242190000001, 9.167924299999985]

**Comment by natedoesweb** [comment]
Interesting. I've always had mine set to 5 seconds and I'll only get No result after about an hour

**Comment by brettstack** [comment]
I wasn't throttling at all. After throttling to every 300ms, I no longer
get this. Although still on login I will occasionally...

**Comment by trickpattyFH20** [comment]
~~I consistently get it on login but I put a timeout fallback after login calls and it all seems to work fine! thanks everyone.~~

I stopped getting the empty response, instead, I started getting a response but with 0 pokemon and 0 pokestops no matter where I go.

**Comment by elijthomas** [comment]
I get this too, I've tried throttling my requests to 5 seconds between then and still get no result every second request

**Comment by andnp** [comment]
I too was seeing this problem. I resolved it for myself by limiting all of my requests (encounter, catch, etc) to one request every 3 seconds. Haven't seen a `no response` since.

**Comment by brettstack** [comment]
I changed mine to 10rps with retry logic and works well. Also added retry
logic to signin - the fact that it happens on signin makes me think it's
not entirely a throttling issue. Might be worth adding retry as an option
for the lib instead
