### ISSUE TITLE
Illegal buffer

### ISSUE THREAD

**Issue by sau00** [Armax/Pokemon-GO-node-api#184]
Time to time getting this kind of error

node_modules/bytebuffer/dist/bytebuffer-node.js:346
            throw TypeError("Illegal buffer");
            ^

TypeError: Illegal buffer
    at TypeError (native)

**Comment by jiaming-jx** [comment]
It's because server dropped your request.

> Yesterday Niantic implemented a throttling system of 3 requests/second (I believe this is the limit, correct me if wrong) per account.
> https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2632

**Comment by firanto** [comment]
I see. I guess we just need to catch it and continue the loop... :)
