### ISSUE TITLE
s2geometry & npm ERR! argv

### ISSUE THREAD

**Issue by abrargaming** [Armax/Pokemon-GO-node-api#196]
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\User\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "pokemon-go-node-api"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s2geometry-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s2geometry-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s2geometry-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\Desktop\test\npm-debug.log
[npm-debug.txt](https://github.com/Armax/Pokemon-GO-node-api/files/398381/npm-debug.txt)

**Comment by billyriantono** [comment]
please open issue in : https://github.com/billyriantono/s2geometry-node not in here and make sure you have installed all requirement : https://github.com/billyriantono/s2geometry-node#windows-user 😄

**Comment by st0ffern** [comment]
@abrargaming https://github.com/stoffern/pokemongo-api = pure js with all commands working (Gym, PokeStop, catching, incubating and so on)
