### ISSUE TITLE
Hearbeat method returns hb object in callback with empty cells array only, everytime...

### ISSUE THREAD

**Issue by externuz** [Armax/Pokemon-GO-node-api#197]
It is an `hb` object from Heartbeat callback:
`{ cells: [] }`
Few hours ago hb was full of other objects, but now he is empty. What I am doing wrong?

**Comment by devmanny** [comment]
are you running your code at heroku or aws?

**Comment by ArEnSc** [comment]
The api is broken https://www.reddit.com/r/pokemongodev/comments/4vl6sl/getmapobjects_changes_made_in_niantic_update/

**Comment by externuz** [comment]
No, it is not a Heroku or Aws, it is my localhost )

**Comment by externuz** [comment]
It looks like there is no way to get more than ONE valid response from API at 5 seconds from 1 IP address. I am using multithreading scan (every thread is uni account). It works fine, when I use 1 or 2 threads. But when I try to use 4 threads, API return only empty cells.

**Comment by falazar** [comment]
too fast, server side stuff there, will give back empty stuff with no errors after awhile.

**Comment by rtw** [comment]
I'm getting exactly the same thing, its been running on AWS via a proxy for about a week now but started getting back only empty responses sometime overnight.  

Is this to do with changes to the API [AHAAAAA issue](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3403?issuecomment=237372013#issuecomment-237372013) ?

**Comment by billyriantono** [comment]
i thinks it's because API Changes, please wait until we fix it .

**Comment by predator747** [comment]
Infos:
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
https://docs.google.com/document/d/1gVySwQySdwpT96GzFT9Tq0icDiLuyW1WcOcEjVfsUu4/preview
