### ISSUE TITLE
Heartbeat dont show Forts in near

### ISSUE THREAD

**Issue by Luzifix** [Armax/Pokemon-GO-node-api#202]
Hey,

you know why the Heartbeat dont show more any Forts in my near?
My is not banned i try it first with the original App than with your Api and after this again with the original App. In the App i see any Pokestop and Arena but with the API i become only a empty object http://pastebin.com/3MsLNwY3

**Comment by zckrs** [comment]
https://github.com/Armax/Pokemon-GO-node-api/issues/200
