### ISSUE TITLE
Stuck on api_req

### ISSUE THREAD

**Issue by williamokano** [Armax/Pokemon-GO-node-api#203]
Hey guys, I'm trying to use the API but after the login (on init) the script tries to call `self.GetApiEndpoint` which uses the `api_req` function.

I was debugging and noticed that the `self.request.post(` is getting stuck when sending the message to the niantic server.

I loggedIn which PTC provider as the example showed, nothing happened.

Hope you can fix it :)

**Comment by LJeremy** [comment]
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
