### ISSUE TITLE
Fix the heartbeat

### ISSUE THREAD

**Issue by Luzifix** [Armax/Pokemon-GO-node-api#205]
Hey,

can anyone fix the Heartbeat. On reddit is the new code in Python public
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by BlackWolf** [comment]
It seems they published a new version of the PGO API (for Python) here: https://github.com/keyphact/pgoapi/tree/master/pgoapi

But since the node API seems to be a port of the python API I suppose it will take a while to convert it

**Comment by WesVleuten** [comment]
It would be in our best interest to make this top priority

**Comment by Nico-Nico-FR** [comment]
Hello, anyone can convert PGO api Python into PGO api Node please?

**Comment by dnnspaul** [comment]
Calm down guys, the API were just cracked.

**Comment by SpencerSharkey** [comment]
working on this

**Comment by Nico-Nico-FR** [comment]
Thank you guys ! You're awesome

**Comment by Luzifix** [comment]
Thx :)

**Comment by dnnspaul** [comment]
FYI, updates: https://discordapp.com/channels/208930747044724737/208930747044724737

**Comment by starkevin** [comment]
@DatN3xus 
You sure that's right? Seems empty...

**Comment by dnnspaul** [comment]
Go in and ask Spencer for an update, you'll see :)

**Comment by starkevin** [comment]
No, I mean it takes you to an empty Discord channel.

**Comment by SpencerSharkey** [comment]
submitted a PR for this: https://github.com/Armax/Pokemon-GO-node-api/pull/207

**Comment by Nico-Nico-FR** [comment]
Thank you SpencerSharkey !

**Comment by SpencerSharkey** [comment]
the only problem I can see that's left to fix up is the auth_ticket expiration. let me know if any of you run a  client for 30+ mins and experience a logout/forbidden

**Comment by starkevin** [comment]
@SpencerSharkey 
Thanks for that. I got pretty close myself using your node-pogo-signature library, but missed that it's auth_ticket now, not auth_token.

Good work mate. :+1:

**Comment by SpencerSharkey** [comment]
It still uses the auth_info message for the initial call to provoke a response with auth_ticket, which should be used for subsequent requests until it expires. Once expired send the auth_info message again and repeat.

**Comment by reecube** [comment]
@SpencerSharkey Very good work, thanks a lot! Do you know how long the auth_ticket is valid until it expires?

**Comment by lukasolson** [comment]
Thanks @SpencerSharkey! You rock. Can we republish to NPM?

**Comment by tdunkel** [comment]
nice work @SpencerSharkey ! Am I wrong or is the example.js still not finding any pokemons?

**Comment by SpencerSharkey** [comment]
@reecube I think it's around 30 minutes... looking into auto-renewal atm.

**Comment by williamokano** [comment]
The heartbeat is now getting the nearby pokemons?

I only got empty lists for forts and nearby pokemons.

**Comment by delmotte** [comment]
the same for me

**Comment by SpencerSharkey** [comment]
until there's an npm release you'll have to manually install the module via the git url:
`npm install --save https://github.com/Armax/Pokemon-GO-node-api.git`

**Comment by starkevin** [comment]
@williamokano  @delmotte 
Are you using PTC accounts? Make sure you've accepted the terms.

You'll need to clone this repo until @Armax pushes to NPM.

**Comment by avatsaev** [comment]
there is still something wrong with it, i often get empty responses with this version: tested with this implementation: https://github.com/avatsaev/pokego-scan-api

wild_pokemon and map_pokemon are very often empty, **wild_pokemon** being the most important data because it contains coordinates and the timers

**Comment by BlackWolf** [comment]
just as a sidenote, there seems to be a limit on how often you can do heartbeats. For me, if I query more often than every 5 seconds, I get either empty responses or heartbeat errors. Just saying :-)

**Comment by starkevin** [comment]
The scan time is 5 seconds. Anything lower returns nothing.
