### ISSUE TITLE
Nearby pokemons

### ISSUE THREAD

**Issue by williamokano** [Armax/Pokemon-GO-node-api#210]
Hi Everyone (again).

I was following the thread of the Unkown6 and, guys, you're awesome.

The API is now functional but, I noticed that the NearbyPokemons and the Forts array are always coming empty.

Is this a bug?

**Comment by avatsaev** [comment]
just tried, getting the same results, an empty array, how can i scan nearby, and get lon/lat coordinates and timestamp when the pokemon disapears?

**Comment by delmotte** [comment]
the same for me

**Comment by delmotte** [comment]
Ok, I think it's the npm module is not updated yet, using `git pull` do the trick ;)

**Comment by avatsaev** [comment]
confirming, npm module not updated, i did this in the package.json and it seems to work for now:

```
"dependencies": {
    "pokemon-go-node-api": "https://github.com/Armax/Pokemon-GO-node-api.git"
 }
```

sometimes the scan still returns empty arrays for some reason.

**Comment by SpencerSharkey** [comment]
@avatsaev sometimes they can return empty if scans go too fast

**Comment by lucassabreu** [comment]
looks like the 200 meters problem is back, i tried at two locations and still 200 meters
1[+] There is a Venonat at 200 meters
1[+] There is a Rattata at 200 meters
1[+] There is a Goldeen at 200 meters
1[+] There is a Ekans at 200 meters
1[+] There is a Caterpie at 200 meters

other place:
1[+] There is a Spearow at 200 meters
1[+] There is a Pidgey at 200 meters
1[+] There is a Spearow at 200 meters
1[+] There is a Pidgey at 200 meters

**Comment by avatsaev** [comment]
@SpencerSharkey gotcha

**Comment by ghost** [comment]
@lucassabreu Back? Was it ever gone?

**Comment by lucassabreu** [comment]
okey then, i thought it was solved in the past, sorry for this then

**Comment by williamokano** [comment]
@avatsaev working with the direct dependency I get an error about the device id

```
/home/william/projetos/pokemon/node_modules/pokemon-go-node-api/poke.io.js:147
        device_id: self.playerInfo.device_info.device_id,
                                              ^

TypeError: Cannot read property 'device_id' of null
```

**Comment by billyriantono** [comment]
https://github.com/Armax/Pokemon-GO-node-api/pull/208 please refer to this @williamokano

**Comment by williamokano** [comment]
@billyriantono Thanks
