### ISSUE TITLE
Is any IP block from server if submit too many requests with different accounts?

### ISSUE THREAD

**Issue by OctHex2016** [Armax/Pokemon-GO-node-api#217]
I use 40 PTC accounts to scan CatchablePokemon in small area with thread. However, after the thread run once, the IP seems get ban by Niantic. What is the best way to scan a large zone?
Also what is the best way to change location and getCatchablePokemon with thread?

**Comment by ChenLi0830** [comment]
Hi @OctHex2016, I have the same question as you do, did you find a solution of it? Thanks

**Comment by explooosion** [comment]
me too, when I  catchpokemon , always  return 'Catch Flee '
maybe soft banned
