### ISSUE TITLE
Npm install not working on ubuntu 16.04 stuck at make: Leaving directory

### ISSUE THREAD

**Issue by maantje** [Armax/Pokemon-GO-node-api#218]
When trying to install the package on the deployment server running ubuntu 16.04 it is getting stuck at `make: Leaving directory '/var/www/html/laravel/app/node/node_modules/s2geometry-node/build'
gyp info ok.` Quiting the process and trying to run the code results into `Error: Could not locate the bindings file.`

Installling the package on my local osx development machine works fine.

**Comment by billyriantono** [comment]
did you have gcc ? or build-essentials installed ? npm install -g npm@next ? 😄

**Comment by maantje** [comment]
@billyriantono 

Thanks for your reply I had build-essentials. I did `npm install -g gcc` now and `npm install -g npm@next` but it is still stuck at the same point.

**Comment by xakiru** [comment]
Try this : npm install git+https://github.com/Armax/Pokemon-GO-node-api.git

**Comment by xakiru** [comment]
I got an other issue now when trying to run example.js: 

> # node example.js
> 
> /home/pokego/node_modules/pokemon-go-node-api/node_modules/node-pogo-signature/lib/U6Encrypt.js:10
>     sub_fnc1(buffer, data)
>             ^
> SyntaxError: Unexpected token (
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/pokego/node_modules/pokemon-go-node-api/node_modules/node-pogo-signature/lib/utils.js:5:21)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)

**Comment by maantje** [comment]
@xakiru `npm install git+https://github.com/Armax/Pokemon-GO-node-api.git` Did the trick! thank you very much.
