### ISSUE TITLE
Login with Google account 

### ISSUE THREAD

**Issue by asantos00** [Armax/Pokemon-GO-node-api#22]
Hi!
Can I login using a google token?

I don't know my password because I've signed in with google account, and the same password as the google acount does not work, have you tried it?

Thanks!

**Comment by Armax** [comment]
No atm you can't you should provide a valid password :/

**Comment by asantos00** [comment]
Yeah, i've read some of the code and now it makes sense. Is that because
the google play services (gpsauth) doesn't play well with node? It looks a
bit tricky to use it.

Thanks for the project!

**Comment by trickpattyFH20** [comment]
google auth is fine with node, the feature just hasn't been implemented here yet

**Comment by asantos00** [comment]
​Ok, I've done some things with google oauth lib in node. If i got a valid
token from there, can I use it to access pokemon go servers? Even if I have
to make a small PR for your lib to use that?

Thanks

**Comment by trickpattyFH20** [comment]
someone already began work on this, take a look at #14 I would try to add on to the work they started there

**Comment by Armax** [comment]
We already have a google login method, we can't use the standard libs because they are not supposed to work without user interactions; as you can see at logins.js line 54 for the token we also use the client_secret
