### ISSUE TITLE
self.GetPokemons(); – TypeError: Illegal buffer

### ISSUE THREAD

**Issue by c4b4d4** [Armax/Pokemon-GO-node-api#23]
I started playing with self.GetPokemons(); but it's throwing an `TypeError: Illegal buffer` error when trying to execute it.

**Comment by trickpattyFH20** [comment]
@kzka90 I get the same error :/ seems like Arm4x is hard at work on it though, I'm sure it'll be ready soon

**Comment by Armax** [comment]
self.GetPokemons and self.Heartbeat are still in development, we are porting the s2 geometry library to node.js (used to crete a cell id from lat/long) because the only one avaiable is broken :C

**Comment by maxnowack** [comment]
mapbox/node-s2#81 looks promising :)
