### ISSUE TITLE
ES6 class pattern

### ISSUE THREAD

**Issue by maxnowack** [Armax/Pokemon-GO-node-api#24]
I'm wondering why you don't use some es6 features like classes in this project. Is there a reason for this?
es6 classes are supported since node 4 (which is LTS at this moment)

**Comment by georules** [comment]
Send a pull request with your suggestions :)  open source!  What specifically would be better in this code using the class feature?

I'd personally not suggest to ever use classes, but that's my preference.

**Comment by trickpattyFH20** [comment]
I'll throw in my 2 cents: typescript and ES6 classes are great, but considering the nature of the project and the fact that at any moment the endpoints, protocols, etc. could change, I think that whatever design patterns the contributors are comfortable with are the best ones to go with. It seems like at this point the big hurdle is reading data through the buffer correctly and reliably.

**Comment by Armax** [comment]
Usually I prefer to use pure node.js callback with an OOP like structure

**Comment by jimmywarting** [comment]
yield, generators, async, await, promise, es6 classes, node-fetch is my preference

And also the use of [async-classes](https://github.com/danielstjules/async-class)

**Comment by stoffern** [comment]
cc @maxnowack ES6 repo comming here: https://github.com/stoffern/pokemon-go-api
