### ISSUE TITLE
Allow the use of a token to authenticate with Google

### ISSUE THREAD

**Issue by aidangoettsch** [Armax/Pokemon-GO-node-api#248]
Currently, the API only allows direct entry of Google credentials to the API. It would be nice to be able to input only a token to allow apps to appear less sketchy.

**Comment by aidangoettsch** [comment]
Seems like this is implemented in #230. Don't see any other issues on this so I'm going to leave this open.

**Comment by jiaming-jx** [comment]
Sadly, I don't think this repo is under proper maintenance anymore...

**Comment by foxinstinct** [comment]
@LASkuma can we contact the author of this repo and ask if he could just transfer it to someone who wants to maintain it?

**Comment by foxinstinct** [comment]
@LASkuma I cloned your forked version of this repo, I got it set up correctly and I was sending the `JWT Token` from `firebase` auth login with google. But I was getting a `Error: invalid_grant` error. Any Idea?

**Comment by jiaming-jx** [comment]
Would you please tell me how to reproduce the error? My online example works pretty fine ATM. http://7few.com
