### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by NelsonGaldeman** [Armax/Pokemon-GO-node-api#252]
I tried to run example.js (tried with google and ptc credentials) and I always got:

![ss 2016-08-24 at 02 48 57](https://cloud.githubusercontent.com/assets/9610178/17919670/918b9024-69a5-11e6-828a-ff0bf0f57de8.png)

**Comment by RedSparr0w** [comment]
https://github.com/Armax/Pokemon-GO-node-api#installation--usage

If downloaded the zip from here

```
npm install
```

otherwise

```
npm install pokemon-go-node-api
```
