### ISSUE TITLE
EvolvePokemon : error regarding cp_multiplier

### ISSUE THREAD

**Issue by litil** [Armax/Pokemon-GO-node-api#254]
I have an issue with the EvolvePokemon method. When I tried to evolve a pokemon, I had an error regarding the id field, I fixed it thanks to the comment from in this issue : #194 .

Now, I have the same kind of error, but this time regarding the cp_multiplier : 
`Error: Illegal wire type for field Message.Field .ResponseEnvelop.Pokemon.cp_multiplier: 5 (1 expected)`

I tried to replace int32 cp_multiplier with float cp_multiplier but I had "Illegal buffer" error.

Any idea? thanks

**Comment by ameyer** [comment]
Here is the proto I have been using. 

[proto file](https://gist.github.com/ameyer/11cc8f70fa3db43dfb3f001b4b11c869)

And the function I use:

```
function evolve(pokemon){
    var id  = pokemon.id;
    var cp = pokemon.cp;
    var pokemon_id = pokemon.pokemon_id;

    pokeAPI.EvolvePokemon(id, function(err, result){
        if (err){
            printError("evolve",err);
        }else{
            if(result.Result ==  1){
                var pokemon = result.EvolvedPokemon

                console.log(chalk.blue("\tevolved to a "+monsters[pokemon.pokemon_type].name+" with the  CP of "+pokemon.cp));
            }else{
                console.log(result);
            }
        }
    });
}
```

**Comment by litil** [comment]
Thanks a lot @ameyer with this proto file, the evolve function works!
