### ISSUE TITLE
GetPokemons method does not work properly

### ISSUE THREAD

**Issue by sadist007** [Armax/Pokemon-GO-node-api#29]
GetPokemons method throw TypeError("Illegal buffer")

**Comment by Josebaseba** [comment]
@sadist007 https://github.com/Armax/Pokemon-GO-node-api/issues/23 They're working on it, give them time, they're doing a great work.

**Comment by space87** [comment]
Why close a issue thats not fixed ?

**Comment by trickpattyFH20** [comment]
@space87 it's not a bug, it's an undocumented and incomplete feature that is a work in progress

**Comment by Armax** [comment]
Because this is the fourth issue where someone is asking for an undocumented method, if you check the commit log you can see "partial heartbeat"
