### ISSUE TITLE
Commit time log

### ISSUE THREAD

**Issue by jdpnielsen** [Armax/Pokemon-GO-node-api#3]
Just a small fyi - something is funky with your commit timestamps, which messes up the commit log. 

![Commit log](http://i.imgur.com/iacGZcg.png)

Try checking your system time http://stackoverflow.com/questions/20081916/github-shows-wrong-time-of-commits

**Comment by Armax** [comment]
My hackintosh have a wrong system time, but I merged from the browser, anyway I think is not a huge problem
