### ISSUE TITLE
SetLocation

### ISSUE THREAD

**Issue by marcianosr** [Armax/Pokemon-GO-node-api#32]
Hi! 

This may sound stupid, but how does the setLocation function actually work? 

I have this code: 

```
Pokeio.SetLocation(location2, function(err, location){
          if (err) throw err;
          console.log('err' + err);
          console.log(location);
          console.log('location2');
          console.log(location2);

          location.latitude = 52.40937;
          location.longitude = 4.895058;
          location.altitude = 0;

          console.log(location);


        });
```

What does it actually do in the game? 

Thanks.

**Comment by Armax** [comment]
atm this method is used to change the location in the playerInfo json created for the player, is not yet changing the location in game, not yet because heartbeat send also a position update so when we will complete the heartbeat method SetLocation will update in-game location too

**Comment by marcianosr** [comment]
allright, thanks!

**Comment by elijthomas** [comment]
Do you know what the eta is on finishing the heartbeat ?
