### ISSUE TITLE
Dont work "npm install pokemon-go-node-api"

### ISSUE THREAD

**Issue by Luzifix** [Armax/Pokemon-GO-node-api#39]
Hey,

the command "npm install pokemon-go-node-api" dont work more after the 1.2.5 patch here is the npm-debug.log ( http://pastebin.com/xTGQ43Eq )

**Comment by d-pollard** [comment]
Your node version looks to be really outdated. Even if you were able to install the package, you couldn't run it as most of it has been translated to ES6. I suggest updating your node first

**Comment by Bart-0110** [comment]
Uninstall node and install the latest current version. [`Link`](https://nodejs.org/en/download/current/).

This repo requires es6 which is supported in node since version 5

**Comment by Luzifix** [comment]
ok thx for your help, i try it now :)

**Comment by Luzifix** [comment]
Hmm...new error...yeah :D
Console: http://pastebin.com/uLjBDrTS
npm-debug.log: http://pastebin.com/N0qP9JcQ

i install Python 2.7.12 & add it to the windows env

last day work anything fine but now nothing work :(

**Comment by mcoquet** [comment]
FWIW, this works fine for me.

**Comment by Luzifix** [comment]
i dont know why but now it works, thx for your help :)
