### ISSUE TITLE
How to obtain the data of nearby pokemon

### ISSUE THREAD

**Issue by pogotracker1** [Armax/Pokemon-GO-node-api#41]
Installed and run the app through the example configuring my email, password, google provider and adding a valid location. Everything runs smoothly. Expected that the "heartbeat" function would return me an array of nearby interest objects, but it returns this:

<img width="725" alt="screen shot 2016-07-20 at 8 37 59 am" src="https://cloud.githubusercontent.com/assets/20561218/16992730/56cb2ef6-4e55-11e6-969f-48f93b8261fc.png">

cells array of objects with some properties, but most of them are empty. Am I using the wrong function? how can I get the data of nearby pokemon?

**Comment by segura2010** [comment]
heartbeat is in development, so it doesnt work yet

**Comment by pogotracker1** [comment]
Should I close the issue then? Or should we keep it here until we know it's not working? Also if I can have some pointers I would gladly help in the development

**Comment by segura2010** [comment]
@pogotracker1 heartbeat is in development and doesnt work yet (https://github.com/Armax/Pokemon-GO-node-api/blob/master/poke.io.js#L233), but i dont know if it should return near pokemons, pokestops and/or forts, so i dont know if it is the function you should use to retrive this kind of data. 

we can try to keep it opened and ask to @Armax what heartbeat do. Also, i would like to know if heartbeat will give us pokestops info and near pokemons info, and if they will add support to catch pokemons. (I would like to develop a web app bot)

**Comment by space87** [comment]
The heart beat is in dev and is working but the heart in the code only runs once at moment put it in a interval and youll see stuff come back as a temp fix

**Comment by benjdlambert** [comment]
It it not just rate-limiting? if you do `setTimeout` then do `.Heartbeat` it works.

It will only do the current cell from what I can see in the code though. It doesn't do multiple requests around you (I think)

**Comment by brettstack** [comment]
@benjdlambert you have it working with `setTimeout`? I've set coords for a known gym location and it's not coming back in `Forts` - I also set coords to a location where I knew a Pokemon was currently and it also did not return.

**Comment by happyDemon** [comment]
using set timeout or set interval does return data, however I'm not sure how correct that data is if I compare it with different sites that got it working.

**Comment by havrylenkok** [comment]
```
heartbeat.cells[0].WildPokemon
heartbeat.cells[0].MapPokemon
heartbeat.cells[0].NearbyPokemon
```

But i'm not sure what will do return pokemon because when i'm trying to use Heartbeat each of those things is empty array.

**Comment by Armax** [comment]
I did it in the example :)

**Comment by firanto** [comment]
It seems that the object is scattered around cells. I've got 21 cells.

Some empty.
Some contain Fort (either PokeStop or Gym since it has both gym point and lure property).
Some contain NearbyPokemon (this should be ones which shows on the nearby window, since they only have fixed distance around 200m, three feet icon I guess)
But none of them contain MapPokemon and WildPokemon. So I don't know what these naming means.
And some contain SpawnPoint which only contain lat-long coordinate without any reference what is spawning in these coordinates.

Anyone has any reference to what these data is? I see at the python version that they can show information about certain pokemon spawned on exact location (lat-long).

**Comment by happyDemon** [comment]
You need try the the CatchablePokemon instead of NearbyPokemon.
both return different pokemon for me.
however the ExpirationTimeMs is never null in CatchablePokemon

**Comment by firanto** [comment]
Yup. I think it should be that. I didn't see that property (Catchable) on the cells though. Maybe I miss it. I'll look into it later.

EDIT: Ok. It seems that the CatchablePokemon property is missing from the cells in the heartbeat.

**Comment by brettstack** [comment]
I'm also not seeing a "CatchablePokemon" prop.
