### ISSUE TITLE
"npm install pokemon-go-node-api" doesn't work

### ISSUE THREAD

**Issue by kyungbaekim** [Armax/Pokemon-GO-node-api#45]
I have node 6.3 and npm 3.10.3 and it keeps giving me below error

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`

Can someone help me with this error?

**Comment by JimFung** [comment]
shot in the dark, you're using a mac? might have to go update XCode if you are.

**Comment by gallexme** [comment]
might using win10 and newest nodejs?
u will need to compile bignum for yourself
so install visual studio (2015)
and install openssl 64 bit (for libeay.lib) (or how its called)
and try again
also you may just send us your npm-debug.log

**Comment by gallexme** [comment]
#50 
as this one is removing bignum dependency it may be fixed anyways soon
