### ISSUE TITLE
What do you feel about a promisified api?

### ISSUE THREAD

**Issue by jimmywarting** [Armax/Pokemon-GO-node-api#47]
Would loosen up the callback hell, what do you think?
Voting?

**Comment by Armax** [comment]
We love the callback hell <br><br>
“If you are going through hell, keep going.” 
― Winston S. Churchill

**Comment by jimmywarting** [comment]
Seeing people up vote this i think it should be worth considering reopen this...

**Comment by Armax** [comment]
Almost every dev on node_dev channel prefer to not use ES6 just a few @billyriantono @jdpnielsen and more

**Comment by st0ffern** [comment]
@Armax well. Normal people write ES6.. and if you wanna do it vanilla JS then go 
`babel src.js --vanilla.js
`
ES6, 7 and 8 is the future
