### ISSUE TITLE
Error first callbacks

### ISSUE THREAD

**Issue by jdpnielsen** [Armax/Pokemon-GO-node-api#5]
I just saw that your mentioned adding in error handling in the #4.

I am currently working a pull request adding error first callbacks. Do you have any preferences for the error returned?

**Comment by Armax** [comment]
Mm no, maybe just the classic function(err,res)

**Comment by jdpnielsen** [comment]
Yeah, that's what i meant. Would you prefer instances of Error or plain objects with a message and such?

**Comment by Armax** [comment]
Instances of Error should be fine
