### ISSUE TITLE
Please, ES6 or not ES6 but not both

### ISSUE THREAD

**Issue by segura2010** [Armax/Pokemon-GO-node-api#52]
In the last pull request some ES6 syntax have been added, forcing to update to node 6.3.0. It has created a lot of problems, people asking why doesnt work #51 , people with problems compiling #45 .. So i would like you decide if you will use ES6 or not, if not, please, remove these changes which are causing a lot of problems.

Personally I prefer not to use ES6, but if you decide to use it i am ok also.

**Comment by gallexme** [comment]
#51 I dont think that this one is Related
its just that the bignum maintainer does not provide for all node/os versions a pre compiled binary

Also @Armax stated that he is against ES6 and its syntactic sugar(#30 #48)

**Comment by Josebaseba** [comment]
We should respect the author's opinion. If they feel more confortable with es5, let's go with that. As the users of the package, what to we earn with es6? Nothing really, and if we want contribute the code right now is really easy to understand.

Btw, since they move to es6, appeared more and more issues related with the topic, and that doesn't help.

**Comment by Bart-0110** [comment]
#45 has isn't an ES6 problem. Even if we keep using es5 you should upgrade to node >5 because node 4 has horrible dependencies support. Requirements in requirements in requirements, this leads to map problems in windows. Node >5 doesn't do that. It has a more efficient system to pull in the requirements.

**Comment by stoffern** [comment]
Setting up a ES6 repo here.. :)
https://github.com/stoffern/pokemon-go-api

**Comment by jimmywarting** [comment]
> Setting up a ES6 repo here.. :)
https://github.com/stoffern/pokemon-go-api

Thanks @stoffern i'm going to contribute to your repo instead

**Comment by Armax** [comment]
Still trying to understand why you need to create an other repo just for ES6 when for the end user there aren't any changes, but ok

**Comment by jimmywarting** [comment]
> Still trying to understand why you need to create an other repo just for ES6 when for the end user there aren't any changes, but ok

@Armax you are against ES6 and its syntactic sugar (#24 #30 #48)

some prefer to work with es6

**Comment by Armax** [comment]
@jimmywarting seriously why we should use ES6 if we are not comfortable with it and we prefer the old one, atm there are no differences in perfomance and I think is faster to read

**Comment by st0ffern** [comment]
@Armax if it is faster to read so keep doing ES5 ;)

**Comment by gallexme** [comment]
@Armax  actually im not sure that most people are comfortable without es6,
me personally only learned es6+ as every lib/framework I use usese es6+ features/ is written in es6
but im also fine with es5

**Comment by Armax** [comment]
also there aren't differences for the end user, It's just for the devs behind the project, so why should we use it if we don't want to, you have been spamming ES6 in our issue for days, you have  been spamming your repo that is a copy paste from us and other pokemon go projects (before saying "you are a tejado clone" we know him and he is in the readme). ES6 or ES5 matter only for contributors and no one is forced to contribute

**Comment by gallexme** [comment]
ES6 or not has differences  For Endusers(API users(devs))
or who do you target with your API ?
if u have Callbacks or Promises or generators, classes etc  is a difference

**Comment by jimmywarting** [comment]
Don't use promises for instance... resulting in not being able to use async/await or coroutine/co/spawn

**Comment by st0ffern** [comment]
``` js
doSomething('withMe')
.then(res => JSON.parse(res))
.then(json => json.subbie)
.then(res => console.log(res))
.catch(err => console.log('uuuups! we got an error'))
```

> that beats the hell out of callback hell

**Comment by Armax** [comment]
As we said tons of times, we prefer the old style callbacks and ES5, there are a lot of libs out there that don't use ES5, do you want ES6? just make your ES6 version, but instead of spamming under our issue maybe you should start crediting all the work that you copy pasted

**Comment by marcianosr** [comment]
Use ES6 if you want ant transpile it back to ES5, good enough right?

**Comment by space87** [comment]
I agree armax. Im dont mind either one still not confortable on es6 fully yet. Think your doing a great job so far and some of thw guys working on s2 report has done amazing. I agree you go with whats comfortable only thing i would say is just dont pr the stuff as you aceptex thw pull request of es6 stuff next time just dont acept ☺

**Comment by andnp** [comment]
The one advantage of es6 is that it helps avoid a few variable scoping issues. PR #81 added a few bugs because they were relying on a variable outside of it's scope. There were no useful warnings because old javascript allows this.

That being said, I'll change my PR to not use es6 if that is the author's wishes.

**Comment by st0ffern** [comment]
@andnp if you are into ES6, then there is a repo here https://github.com/stoffern/pokemon-go-api
