### ISSUE TITLE
Google login 403

### ISSUE THREAD

**Issue by happyDemon** [Armax/Pokemon-GO-node-api#53]
I'm getting a 403 response when I'm trying to login with my google account, any tips on how to fix this?

Using correct credentials by the way.

can someone push me the right way?

**Comment by segura2010** [comment]
do you have two factor authentication?

**Comment by happyDemon** [comment]
is that what's stopping it? damn

**Comment by segura2010** [comment]
yes, if you have two factor authentication it will return 403 error.. You can generate and use an app password (https://support.google.com/accounts/answer/185833?hl=en) :)
