### ISSUE TITLE
WildPokemon always seems blank for me.

### ISSUE THREAD

**Issue by jatinhariani** [Armax/Pokemon-GO-node-api#59]
Results differ from the wildpokemon spawning in https://github.com/AHAAAAAAA/PokemonGo-Map. WildPokemon always seem to be a blank array for me.
Nearby Pokemon on both seem to be the same.
Maybe because the prototype is different? The wild pokemon on that app also gives a latitude and longitude. Would be awesome if this project can have that. #

**Comment by d-pollard** [comment]
This is being looked into - https://github.com/Armax/Pokemon-GO-node-api/issues/57

**Comment by Armax** [comment]
We are working on fixing it, the problem is with the s2 lib
