### ISSUE TITLE
Cannot find module: s2geometry-node

### ISSUE THREAD

**Issue by kfernandes29** [Armax/Pokemon-GO-node-api#63]
Trying to build the latest build is resulting in an error

Cannot find module 's2geometry-node'

[npm-debug.txt](https://github.com/Armax/Pokemon-GO-node-api/files/377031/npm-debug.txt)

**Comment by SzymonLisowiec** [comment]
```
sudo apt-get install build-essential
npm install pokemon-go-node-api
```

**Comment by kfernandes29** [comment]
Does that work in windows? I need to build in windows and push all the node_modules along with the project to my Azure Mobile App Service.

Thanks in advance! @SzymonLisowiec

**Comment by SzymonLisowiec** [comment]
Unfortunately, I don't know how "build-essential" is on Windows.

**Comment by Armax** [comment]
we are still porting the s2 lib to windows

**Comment by coolaj86** [comment]
Fixed in https://github.com/Armax/Pokemon-GO-node-api/pull/165 by using pure JavaScript - no C++ or compiler necessary.
