### ISSUE TITLE
How to manually init?

### ISSUE THREAD

**Issue by coolaj86** [Armax/Pokemon-GO-node-api#75]
In relation to https://github.com/Armax/Pokemon-GO-node-api/issues/69, how can I manually initialize an object (i.e. I already have a valid access token and api_endpoint and don't need to log in again until the token expires)?

I'm thinking it's something like this:

```
var pokeio = new PokemonGO.Pokeio();

pokeio.playerInfo.username = 'johndoe';
pokeio.playerInfo.password = 'secret';
pokeio.playerInfo.provider = 'ptc';
pokeio.playerInfo.accessToken = 'xyz';
pokeio.playerInfo.latitude = 40.36915523640919;
pokeio.playerInfo.longitude = -111.75098587678943;
pokeio.playerInfo.altitude = 0;
pokeio.j = request.jar(new FileCookieStore(path.resolve('/tmp/', pokeio.playerInfo.username + '.pokemongo.json')));
pokeio.request = request.defaults({ jar: pokeio.j });

pokeio.playerInfo.apiEndpoint = api_endpoint;
```

Perhaps the Cookie Jar isn't really necessary? (that would be wonderful if it isn't)

**Comment by firanto** [comment]
I need this as well. Heck, because of the whole init->...->heartbeat thing makes a stateless approach painful (i.e. web service/api).

What I want to accomplish is, user call my api to sign in, and get the token and it's expiration. This way, user can request anything (within time interval, specifically for heartbeat) using that token without the need of re-login.

**Comment by coolaj86** [comment]
We're doing the same thing :)

**Comment by coolaj86** [comment]
Here's how far I got tonight: https://github.com/coolaj86/node-pokemap

I'm not sure if my deserialize isn't working because the servers in my region are down (because the normal way isn't working right now either) or if it's missing some parameters. I'll have to try again in the morning.

**Comment by d-pollard** [comment]
Without the heartbeat, Niantic will be more likely to be able to detect you are a bot and terminate the account.

**Comment by Armax** [comment]
yes you can change almost anything in the playerInfo and it works like a manual init

**Comment by coolaj86** [comment]
@d-pollard:

Why not let this lib focus on being the best way to interface with the API and let the client control the heartbeat?

People open the app, use it for 10 seconds, and close it all the time (or more likely it crashes). Having the browser or client control the request for the heartbeat may add a little bit of latency, but we're talking about mobile phones - latency is always terrible.

@Armax:

Docs for which things are and aren't required to be initialized? Is my list complete?

**Comment by coolaj86** [comment]
I've got the server and client both working now: https://github.com/Daplie/node-pokemap

I haven't implemented scanning yet, but instead of doing it on the backend, I'm probably going to let the web client handle it (just need to understand the logic around the s2cellid stuff a little better so I know the optimal places to reposition the gps coordinates).
