### ISSUE TITLE
Expose Token Expiry

### ISSUE THREAD

**Issue by coolaj86** [Armax/Pokemon-GO-node-api#76]
I believe the refresh_token and access_token both come with expiry times which should be exposed (so we can login again without a failed attempt when the token has expired), but are not yet.

**Comment by d-pollard** [comment]
Yeah, I do this in my repo, maybe I'll fix up this one and submit a commit

**Comment by Armax** [comment]
we are working on this, in the next commit we will push it

**Comment by coolaj86** [comment]
Was this ever pushed?
