### ISSUE TITLE
Safeguarding each callback with try catch

### ISSUE THREAD

**Issue by firanto** [Armax/Pokemon-GO-node-api#77]
When I look at the module's code. There are a lot of multi-level async call using callbacks without any safeguard. If one of those callbacks are throwing exception, the whole thing is collapsed (halted, force closed, crashed). I've try to put a try catch enveloping the init call without any success since it's not the init call who throw the exception, it's subsequent callbacks did (which obviously didn't covered by try-catch block).

**Comment by d-pollard** [comment]
Thus why the library should be promisified. Hoping to get that done either today or tomorrow in my repo.

**Comment by carldanley** [comment]
I just finished publishing a promisified version of my own take on everything; see https://github.com/carldanley/node-pokemon-go-api.

**Comment by Armax** [comment]
@d-pollard maybe forking it, instead of uploading it again will be nice, but at least you give use credits and you used our license.md

**Comment by carldanley** [comment]
Deleting comments doesn't really help you at all.

**Comment by Armax** [comment]
@carldanley our issues are not supposed to be used for spamming your repos, you commented with useless things 3/4 issue and linked your repo, also you take a lot of "inspiration" from our repo and you didn't mentioned/credited us

**Comment by carldanley** [comment]
You must be kidding. I'll disregard that last comment. I started a new repo because yours is sort of a mess; easier to start fresh.

**Comment by Armax** [comment]
No problem if you want to make your own repo without crediting us for a lot of work that you just reused, but at least stop linking your repo under our issues, I found you linking it under 3/4 issues sometimes unrelated.

**Comment by carldanley** [comment]
Whatever you think man; not going to fight with a 19 year old on the internet.

**Comment by Armax** [comment]
My age is unrelated, as I already said, stop linking your repo under our issue, you are not going to help anyone by doing so, you are just trying to get peoples looking at your repo and also didn't give us credits.

**Comment by carldanley** [comment]
Good luck catching up.
