### ISSUE TITLE
OAuth2 Tokens

### ISSUE THREAD

**Issue by Bfindlay** [Armax/Pokemon-GO-node-api#79]
Can we expect to be able to use an Oauth2 token through passport.js or similar?
inputting actual usernames and passwords is not going to work with 2fa

**Comment by coolaj86** [comment]
I've started work web a webserver, which will have JWT (OAuth2/OAuth3/OIDC tokens) built on top of this library here: https://github.com/coolaj86/node-pokemap

I have to go to bed for now, but I'll try to resume Saturday. There needs to be a way to serialize and deserialize the pokeio object (mentioned in other issues #69 #75) before it can be completed.

**Comment by carldanley** [comment]
This is definitely possible but whatever client you use to generate a JWT token will need to conform to very specific settings:

1. https://github.com/carldanley/node-pokemon-go-api/blob/master/src/login.js#L13-L16
1. https://github.com/carldanley/node-pokemon-go-api/blob/master/src/login.js#L28

**Comment by Armax** [comment]
just change playerInfo.accessToken
