### ISSUE TITLE
Decouple geolocation translation

### ISSUE THREAD

**Issue by coolaj86** [Armax/Pokemon-GO-node-api#85]
The async location code should probably be pulled out since this can be done in the browser, mobile app, node client, etc and isn't core to this library.

It just adds weight to this module.

**Comment by coolaj86** [comment]
If you would accept a pull request with adjusted library and example let me know and I'll get that done tonight.

**Comment by Armax** [comment]
@billyriantono

**Comment by Armax** [comment]
atm we prefer to use the location module inside the library because we don't need to handle locations outside it and we have updated information in playerInfo
