### ISSUE TITLE
Neighboring cells only to the west

### ISSUE THREAD

**Issue by brettstack** [Armax/Pokemon-GO-node-api#91]
So I plotted the center points of the neighboring cells and got this [map of neighboring cells](http://maps.google.com/maps/api/staticmap?center=-24.573167+149.977612&zoom=15&size=1024x1024&maptype=terrain&markers=-24.594975,149.972480&markers=-24.592291,149.972480&markers=-24.594343,149.969590&markers=-24.596239,149.978259&markers=-24.593555,149.978259&markers=-24.592923,149.975369&markers=-24.595607,149.975369&markers=-24.587556,149.975369&markers=-24.588188,149.978259&markers=-24.590871,149.978259&markers=-24.590240,149.975369&markers=-24.582188,149.975369&markers=-24.584872,149.975369&markers=-24.585504,149.978259&markers=-24.582820,149.978259&markers=-24.581556,149.972480&markers=-24.580925,149.969590&markers=-24.583608,149.969590&markers=-24.584240,149.972480&markers=-24.576189,149.972480&markers=-24.575557,149.969590&markers=-24.578241,149.969590&markers=-24.578873,149.972480&markers=-24.577452,149.978259&markers=-24.580136,149.978259&markers=-24.579504,149.975369&markers=-24.576821,149.975369&markers=-24.572085,149.978259&markers=-24.571453,149.975369&markers=-24.574137,149.975369&markers=-24.574768,149.978259&markers=-24.566085,149.975369&markers=-24.568769,149.975369&markers=-24.569401,149.978259&markers=-24.566717,149.978259&markers=-24.567506,149.969590&markers=-24.564822,149.969590&markers=-24.568138,149.972480&markers=-24.565454,149.972480&markers=-24.572874,149.969590&markers=-24.573505,149.972480&markers=-24.570821,149.972480&markers=-24.570190,149.969590&markers=-24.568926,149.963811&markers=-24.569558,149.966701&markers=-24.572242,149.966701&markers=-24.571610,149.963811&markers=-24.566243,149.963811&markers=-24.563559,149.963811&markers=-24.566874,149.966701&markers=-24.564191,149.966701&markers=-24.562296,149.958033&markers=-24.564979,149.958033&markers=-24.565611,149.960922&markers=-24.562928,149.960922&markers=-24.570978,149.960922&markers=-24.570346,149.958033&markers=-24.567663,149.958033&markers=-24.568295,149.960922&markers=-24.573030,149.958033&markers=-24.575713,149.958033). Compare that to [another map I have plotted](http://maps.google.com/maps/api/staticmap?center=-24.573167+149.977612&zoom=15&size=1024x1024&maptype=terrain&markers=-24.573167,149.977612&markers=label:S|color:green|-24.57609758500573,149.97071872195852&markers=label:D|color:brown|-24.576403366254294,149.96981575536566&markers=label:G|color:black|-24.576089,149.970974&markers=label:D|color:brown|-24.578574090871324,149.97053812815707&markers=label:P|color:white|-24.577538,149.972099&markers=label:S|color:green|-24.571095327802563,149.9762269488551&markers=label:S|color:green|-24.571263068912955,149.9762269488551&markers=label:G|color:black|-24.572953,149.976075&markers=label:P|color:white|-24.573779,149.975038&markers=label:G|color:black|-24.567194,149.975155&markers=label:P|color:white|-24.566773,149.975794&markers=label:P|color:white|-24.566014,149.976296&markers=label:P|color:white|-24.569003,149.975246&markers=label:P|color:white|-24.569359,149.974926&markers=label:P|color:white|-24.569187,149.974422&markers=label:D|color:brown|-24.568006922300842,149.97360825561213&markers=label:S|color:green|-24.57383827991404,149.97342765794843&markers=label:G|color:black|-24.573057,149.971362&markers=label:P|color:white|-24.570309,149.97158&markers=label:P|color:white|-24.570877,149.971731&markers=label:P|color:white|-24.570923,149.96931&markers=label:P|color:white|-24.570428,149.969943) with the red marker showing the location of the character for that heartbeat. As you can see, the neighboring cells are spanning to the left/west. Is this a bug or am I misunderstanding the intent? I would have assumed it would get neighboring cells in all directions.

**Comment by dotomaz** [comment]
That's because of how [hilbert curve in s2 library](http://blog.christianperone.com/2015/08/googles-s2-geometry-on-the-sphere-cells-and-hilbert-curve/) works. Ultimately if you go a couple of cells back  and a couple next you'll get complete coverage of surrounding cells.

**Comment by brettstack** [comment]
Could you explain with code what you mean, "if you go a couple of cells
back and a couple next"?

**Comment by dotomaz** [comment]
See the `getNeighbors()` function in poke.io.js

**Comment by brettstack** [comment]
That's the function that is generating these west-only cells, so the code there does not help me :(

**Comment by Armax** [comment]
we are still working on the s2 library
