### ISSUE TITLE
Negative value of TimeTillHiddenMs 

### ISSUE THREAD

**Issue by havrylenkok** [Armax/Pokemon-GO-node-api#93]
I'm using code like this to get spawned pokemon on users location

```
 Pokeio.Heartbeat(function (err, hb) {
      if (err) {
        return errorHandler(err, callback);
      }

      for (let i = hb.cells.length - 1; i >= 0; i--) {
            if (hb.cells[i].WildPokemon) {
              for (let j = 0; j < hb.cells[i].WildPokemon.length; j++) {
                  console.log(hb.cells[i].WildPokemon[j].TimeTillHiddenMs / 1000);
                }
            }
       }
});
```

and sometimes get negative values (like `-375492.726`) of TimeTillHiddenMs / 1000. What is the right way to handle them? Didn't have opportunity to locate bug somewhere near mine location so could check what happenning in game at the moment.

**Comment by Elyx0** [comment]
Please note that the heartbeat function is currenly a bit broken. Besides that I found negative TimetillHiddenMs and sometimes the pokemon was there too, maybe it's a response buffer converting issue.

**Comment by BlackWolf** [comment]
From my experience, a negative value here mostly means the pokemon will appear "soon" (in a couple of minutes). At least this is true for me most of the time.

**Comment by havrylenkok** [comment]
Well, i was able to recreate this bug while playing and it's really mean 'pokemon will be spawned soon'.

**Comment by andnp** [comment]
I suppose a possible way to resolve this issue would be to provide an example for how to deal with this in `example.js`.

I have been dealing with it by simply providing a check in the heartbeat function like:

```
for (let j = 0; j < hb.cells[i].WildPokemon.length; j++) {
  if (hb.cells[i].WildPokemon[j].TimeTillHiddenMs > 0) {
    // Do something here (encounter and catch for instance)
  }
}
```

**Comment by WiS3** [comment]
I also got a value of -1. and in game the pokemon was there.. even after some minutes, i still got -1 and the pokemon still there.

If there isn't a confirmed meaning of the negative values, the issue should be reopened till it's figured out.
I just found [this](https://www.reddit.com/r/pokemongodev/comments/4ui7um/pokemon_go_mapscan_optimized_code/d5ri2ot): I will try and check if it is true.

@andnp Your solution just discard every pokemon with a negative value, but as i said, the pokemon was in-game and catchable, so it's not really a solution.

**Comment by andnp** [comment]
I have yet to come across an instance where `TimeTillHiddenMs` was < 0 and I was able to catch the pokemon through the api. I agree that the issue probably shouldn't be closed yet, as no viable solution has been deployed yet.

Unfortunately, until we can figure out the real reason that these pokemon are causing the api to crash, my solution is the only one that I've found that allows my bot to keep playing.

**Comment by WiS3** [comment]
Well, i'm not writing a bot so i don't use the Catch API.
I'm writing a map that display pokemon on the map, and also move the character on the real game.
I was able to catch the pokemon in game, and the `TimeTillHiddenMs` was `-1.`

I also found that after some time it correct itself.. and is no longer negative.

**Comment by andnp** [comment]
Interesting. When you caught the Pokemon in game, did you notice that the
TimeTillHiddenMs field was changing, or was it statically at -1?

**Comment by WiS3** [comment]
I didn't noticed, i will do more testing and see what happens.

**Comment by WiS3** [comment]
@andnp Ok i did some testing. Catching it or not doesn't seem to have any effect.
It however changed after some minutes that i catched.

Probably it is true that those pokemon have a > 15min timer, and while it is > 15min it has a negative value.
But it is strange that with a Catching bot there are problems, while in game not.
