### ISSUE TITLE
's2geometry-node' only works on Mac OS

### ISSUE THREAD

**Issue by reecube** [Armax/Pokemon-GO-node-api#96]
The 's2geometry-node' only works on Mac OS. 
I couldn't install it on Windows nor on Ubuntu. 
Is there any good alternative to this? I've seen this to generate the id's: https://github.com/jonatkins/s2-geometry-javascript/blob/master/src/s2geometry.js
But it doesn't seem to work. I've converted the s2geometry.js to a node module, if you want it?

Hope we could fix this, highly need Ubuntu support for this.

**Comment by jimdubbs** [comment]
A PR was just approved in version 1.3.0 of s2geometry-node which is supposed to address these issues. Have not confirmed myself yet.

**Comment by reecube** [comment]
If someone needs a hotfix for this, change the package.json-file-entry: "s2geometry-node": "github:cypherix93/s2geometry-node#windows-fixes"

**Comment by coolaj86** [comment]
Fixed in https://github.com/Armax/Pokemon-GO-node-api/pull/165 by using pure JavaScript - no C++ or compiler necessary.
