### ISSUE TITLE
EncounterId to GPS-coordinates

### ISSUE THREAD

**Issue by reecube** [Armax/Pokemon-GO-node-api#99]
With the function 'Heartbeat', I get the 'EncounterId' in the callback (for each single nearby pokemon). How can I transform it into GPS-coordinates, or is this even possible?

**Comment by segura2010** [comment]
In each pokemon from "WildPokemon" array, you will have a pokemon with the fields "Longitude" and "Latitude".

Pokemons from "NearbyPokemon" array dont provide the location info until you are close enough (and they will be put on "WildPokemon" array when it occurs)

**Comment by reecube** [comment]
Thank you very much sir!
